name: Build Geode Mod

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Android 32-bit
            os: ubuntu-20.04   # Tady jdeme na ubuntu 20.04 (z roku 2020!)
            target: Android32
          - name: Android 64-bit
            os: ubuntu-20.04
            target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@v1.6.0  # NATVRDO STARÁ VERZE NÁSTROJE
        with:
          target: ${{ matrix.config.target }}

  package:
    name: Package Geode Mod
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Combine build artifacts
        uses: geode-sdk/build-geode-mod@v1.6.0  # NATVRDO STARÁ VERZE
        with:
          combine: true
